# Generated by Django 3.2.4 on 2021-07-05 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rname', models.CharField(max_length=30)),
                ('nitems', models.IntegerField()),
                ('time', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('rsimg', models.ImageField(default='logo.png', upload_to='Restaurantimages/')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Itemlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=50)),
                ('icategory', models.CharField(choices=[('Non-veg', 'Non-veg'), ('Veg', 'Veg'), ('Select item-type', 'Select item-type')], default='Select item-type', max_length=50)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('iimage', models.ImageField(default='logo.png', upload_to='Itemimages/')),
                ('iavail', models.CharField(choices=[('Available', 'Available'), ('Not-Available', 'Not-Available'), ('Select Availability', 'Select Availability')], default='Select Availability', max_length=50)),
                ('rsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant_app.restaurents')),
            ],
        ),
    ]
