# Generated by Django 3.2.4 on 2021-06-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurents',
            name='rsimg',
            field=models.ImageField(default='logo.png', upload_to='Restaurantimages/'),
        ),
    ]
